# Generated by Django 5.1.5 on 2025-09-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('projects', '0002_remove_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='schema',
            field=models.JSONField(help_text='ساختار به فرمت jsonبده محتوا'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contenttype'),
        ),
    ]
