# Generated by Django 5.1.5 on 2025-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_contenttype_slug_alter_contenttype_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
