# Generated by Django 5.1.5 on 2025-09-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contenttype_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
