# Generated by Django 5.1.5 on 2025-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contenttype_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
